Repository mstachniuk/shipkit-workshop, pull requests merged in 2019-01, with the labels that each got.

#14 #4 Floating point support
  src/main/java/com/example/shipkitworkshop/MathUtils.java
Labels: new feature

#15 Unit tests for MathUtils are missing #8
  src/test/java/com/example/shipkitworkshop/MathUtilsTest.java
Labels: quality

#18 Add Readme file
  README.md
Labels: docs

#19 Add Javadoc for MathUtils class
  src/main/java/com/example/shipkitworkshop/MathUtils.java
Labels: docs
